### ISSUE TITLE
[Feature request] Support anonymous download of certain modules

### ISSUE THREAD

**Issue by l2dy** [terralist/terralist#169]
For private networks, it may be desirable to allow anonymous read access of certain Terraform modules and use network ACLs to control access.

One way to implement this is to allow creation of "public" authorities that permit anonymous read access.

**Comment by valentindeaconu** [comment]
Thank you for submitting this request!

This looks doable in my vision: add an optional `public_read` flag for each authority. If a request arrives that tries to read a module/provider, look if the module/provider's authority has the flag enabled and authenticate the request as `anonymous`.

I will include it in [this roadmap item](https://github.com/orgs/terralist/projects/1?pane=issue&itemId=26533568).

Just to confirm, the way I see this:
- Terralist will allow some authorities to be publicly accessible, which automatically includes all providers and modules that are uploaded under that particular authority (read-only);
- Terralist will still be private: creating authorities, uploading artifacts, and reading artifacts from non-public authorities will require authentication;
- Web UI (which will also include the artifacts documentation in the future) will still be private and will require authentication - I think we can also change this in the future, but definitely not now;
- Will become a vulnerability that can be costly: a malicious user can try to take advantage of the storage bucket that's behind Terralist and increase the usage cost - this can be prevented by adding some rate-limiting - I'd say to only add a `warning` for now; 
- Will introduce a breaking change since the database schema will be changed, but the API Keys rework will also introduce some, so I can bundle all of them together in a migration file;

Do you see anything wrong with my proposal? 
Would this proposal achieve your goal?

**Comment by l2dy** [comment]
Yes, it would achieve my goals and the proposal makes sense.

The only nitpick is that if Terralist is deployed to an internal network, risk of the usage cost vulnerability is much lower, because Internet-wide scanning can be avoided and there are usually more valuable targets in the intranet if someone manages to break in.

**Comment by valentindeaconu** [comment]
Yes, in your case it is deployed in an internal network, but the feature is available for any user, even those that deploy it on a public network, so they can expose themselves by using it.

**Comment by valentindeaconu** [comment]
Closing this since it can be tackled with the global anonymous flags added in #195 and released in v0.4.5.
