### ISSUE TITLE
weird bugs when deploying Terralist into Kubernetes

### ISSUE THREAD

**Issue by jsidney** [terralist/terralist#222]
We have just moved our terralist installation into an EKS cluster that uses Istio for networking and karpenter for autoscaling. 
however, we have noticed that there are some really weird bug where terralist fails to launch successfully:
```json
{"level":"error","error":"could not unpack flags: could not convert string tcp://10.100.156.24:5758 into integer: strconv.Atoi: parsing \"tcp://10.100.156.24:5758\": invalid syntax","time":"2024-03-25T07:16:22Z"}
```

has anyone had a similar issue or know how to fix this bug?

**Comment by valentindeaconu** [comment]
This seems to be the error from the IntFlag implementation:

https://github.com/terralist/terralist/blob/92bc29fa4115e1b3873e5ebf1609a20bf7ebc5c9/pkg/cli/int_flag.go#L46

This implementation is only used for ports (mostly) at this moment, and based on the value there, I'm guessing you're setting the `--port` flag (or `TERRALIST_PORT`) to `tcp://10.100.156.24:5758` which is not a valid value (since it cannot be converted to integer). The port should be an integer number, such as `5758`.

**Comment by osherdp** [comment]
@jsidney did you ever understand why it required a service name change?
