### ISSUE TITLE
User can login to UI but Terraform login results in a 403

### ISSUE THREAD

**Issue by danielarcari** [terralist/terralist#225]
We're running terralist on AWS ECS, with the following config:

```
TERRALIST_OAUTH_PROVIDER       = "github"
TERRALIST_GH_CLIENT_ID         = "c9a..."
TERRALIST_GH_CLIENT_SECRET     = "cc5.."
TERRALIST_TOKEN_SIGNING_SECRET = "something"
TERRALIST_DATABASE_BACKEND     = "postgresql"
TERRALIST_POSTGRES_HOST        = "${aws_db_instance.terralist.address}"
TERRALIST_POSTGRES_PORT        = "5432"
TERRALIST_POSTGRES_DATABASE    = "terralist"
TERRALIST_POSTGRES_USERNAME    = "admin"
TERRALIST_POSTGRES_PASSWORD    = "${random_password.terralist_db_credential.result}"
TERRALIST_COOKIE_SECRET        = "somethingelse"
TERRALIST_SESSION_STORE = "cookie"
TERRALIST_URL = "https://terralist.dev.example.com"
URL = "https://terralist.dev.example.com
```

The service starts fine, the UI is presented, users can click "Continue with GitHub" which redirects to the GH auth page, and then successfully back to the terralist UI. However, when running `terraform login terralist.dev.example.com`, users get a generic 403 Forbidden screen. The url below is what's being sent from the login command:

`https://<redacted>/v1/auth/authorization?client_id=terraform-cli&code_challenge=4vr2nnMwgeHUSsKqieSMwJCH3IokBYIifHNO-4Mjfio&code_challenge_method=S256&redirect_uri=http%3A%2F%2Flocalhost%3A10009%2Flogin&response_type=code&state=22b84e09-47c5-5270-f675-1d0bbeadd912`

As far as I can tell, only the [login controller throws this error,](https://github.com/terralist/terralist/blob/7447d60c082c888a290fec543ec83fa3dc887704/internal/server/controllers/login.go#L249) if the session doesn't contain user info. What are we missing here?

**Comment by valentindeaconu** [comment]
Hello!

The code block you linked is not related to the `terraform login` workflow and that's why I'm a bit puzzled. No workflow should throw a basic `403 Forbidden` screen during the `terraform login` command because the entire Oauth workflow is based on redirects, so at best, it will be some 3xx status with an OAuth error (query param). 
- Are you sure you're receiving a 403 status? 
- Can you try to open the link `terraform login` command generated in an incognito window? It's easier to debug if I know the request fails before or after the OAuth provider redirect.
- Are all of your users affected by this issue or is it an isolated case?

The config looks correct, so I don't think it's an issue there, otherwise, the UI would reject the requests too.

**Comment by danielarcari** [comment]
Thanks for the reply, here's the output from my terminal where `login` is being run:

```
XXX:~ someone$ terraform login <redacted>.com
Terraform will request an API token for <redacted> using OAuth.

This will work only if you are able to use a web browser on this computer to
complete a login process. If not, you must obtain an API token by another
means and configure it in the CLI configuration manually.

If login is successful, Terraform will store the token in plain text in
the following file for use by subsequent commands:
    /Users/someone/.terraform.d/credentials.tfrc.json

Do you want to proceed?
  Only 'yes' will be accepted to confirm.

  Enter a value: yes

Terraform must now open a web browser to the login page for <redacted>.com.

If a browser does not open this automatically, open the following URL to proceed:
    https://<redacted>/v1/auth/authorization?client_id=terraform-cli&code_challenge=ErMFBeZbaG3ANh2bcSBRexIWS0BxZJT238ejrb1o44A&code_challenge_method=S256&redirect_uri=http%3A%2F%2Flocalhost%3A10008%2Flogin&response_type=code&state=d3e209b8-5ece-d23d-8b2f-0df28bf814fe

Terraform will now wait for the host to signal that login was successful.ML85:~ someone$ terraform login <redacted>.com
Terraform will request an API token for <redacted> using OAuth.

This will work only if you are able to use a web browser on this computer to
complete a login process. If not, you must obtain an API token by another
means and configure it in the CLI configuration manually.

If login is successful, Terraform will store the token in plain text in
the following file for use by subsequent commands:
    /Users/someone/.terraform.d/credentials.tfrc.json

Do you want to proceed?
  Only 'yes' will be accepted to confirm.

  Enter a value: yes

Terraform must now open a web browser to the login page for <redacted>.

If a browser does not open this automatically, open the following URL to proceed:
    https://<redacted>/v1/auth/authorization?client_id=terraform-cli&code_challenge=ErMFBeZbaG3ANh2bcSBRexIWS0BxZJT238ejrb1o44A&code_challenge_method=S256&redirect_uri=http%3A%2F%2Flocalhost%3A10008%2Flogin&response_type=code&state=d3e209b8-5ece-d23d-8b2f-0df28bf814fe

Terraform will now wait for the host to signal that login was successful.
```

And here's the result:

![terralist_403](https://github.com/terralist/terralist/assets/77171391/a5967ce9-b2c0-42ae-8fea-5d260bc7dd84)

**Comment by valentindeaconu** [comment]
Sorry for the late reply, I had to start with a setup from scratch trying to reproduce this. For me, it works as expected on both web UI and from `terraform login` CLI command.

However, I might have an idea about what's going on, can you please check the following:
1. Terralist is served over HTTPS.
2. `TERRALIST_URL` environment variable is set to the base URL of your Terralist deployment (e.g. `https://terralist.example.com`)
3. The Oauth app callback URL is set to `${TERRALIST_URL}/v1/api/auth/redirect` (e.g. `https://terralist.example.com/v1/api/auth/redirect`).

Also, can you please let me know which Terralist version are you running?

**Comment by danielarcari** [comment]
We are running 0.4.6.
`TERRALIST_URL` is set as indicated (https://terralist.example.com, with our domain), and is using HTTPS behind AWS ALB.
Callback URL is https://terralist.example.com/v1/api/auth/redirect, with our domain.

I also noticed that if I set the GitHub organization flag to our org, I get rejected (even though I am definitely part of our org). This combined with the 403 where the cookie user isn't present, seems to indicate that a user session is never being created in the first place, possibly.

**Comment by valentindeaconu** [comment]
I updated the compose file to v0.4.6 and started again. I cannot reproduce it in the way you're describing the issue, sorry.

Just wanted to mention it, if you're performing `terraform login {terralist-domain}`, there should be no request to `/v1/api/auth/session`, because Terralist is not trying to associate you to a session, but to a token (and it will generate a token for Terraform, to be stored in `$HOME/.terraform.d/credentials.tfrc.json`.

If you isolate the server and try a basic login, you should see the following 3 lines of logs:
```
{"level":"info","method":"GET","path":"/v1/auth/authorization#REDACTED","resp_time":0.103125,"status":302,"client_ip":"REDACTED","time":"2024-04-18T13:45:08Z"}
{"level":"info","method":"GET","path":"/v1/api/auth/redirect#REDACTED","resp_time":928.586688,"status":302,"client_ip":"REDACTED","time":"2024-04-18T13:45:10Z"}
{"level":"info","method":"POST","path":"/v1/auth/token","resp_time":0.8145,"status":200,"client_ip":"REDACTED","time":"2024-04-18T13:45:10Z"}
```

Because that's how it should work:
Terraform calls Terralist (`/v1/auth/authorization`), then Terralist redirects to the Oauth provider (GitHub in this case), then GitHub calls back Terralist (`/v1/api/auth/redirect`), then Terralist calls back Terraform with a code challenge, then Terraform solves the challenge and sends a new request to Terralist (`/v1/auth/token`) to exchange the challenge solution for a token.

As you can see, the exact 3 log lines I see in my tests.

I cannot find any possible flow in which you will get a 403 Forbidden status while trying to `terraform login`. Also, if you're trying to log in to the web UI and get a 403 Forbidden status, you should be redirected back to the login page, instead of seeing a `403 Forbidden` error page.

With that being said, I have some reasons to believe that your deployment is faulty, probably at the AWS ALB level? Can you please double-check it? I will try to investigate more, but as I said, I see no possible flow that will result in a generic 403 response.

**Comment by danielarcari** [comment]
Thanks for the prompt assistance. This turned out to be a problem with AWS WAF, which we had in front of the ALB. Sorry to have bugged you, but maybe this will save someone else some trouble in the future.

**Comment by valentindeaconu** [comment]
No worries, glad I could help and you fixed the issue.
