### ISSUE TITLE
[Feature Request] Support GCS private storage

### ISSUE THREAD

**Issue by loicsikidi** [terralist/terralist#38]
Hello,

A part of my customers use other cloud vendors (eg. GCP, Azure, Alibaba), it would nice to support them in order to be cloud agnostic.

Regarding my roadmap, GCP is a top priority so I'm ready to contribute to create a _Google Cloud Storage_ internal module.

Afterwards, it would be interesting to define what should be possible to [configure](https://github.com/valentindeaconu/terralist/blob/master/example.yaml) for the end-user.

**Examples**:

1. possibility to define a global private storage -> apply to all API resources (modules, providers, etc.) [_which what is currently available_] and authorities
2. possibility to define a private storage at the authority level (eg. authority A uses AWS whereas authority B uses GCS)
3. possibility to define a private storage at the API resource level (eg. AWS for modules and GCS providers)

If you think that this needs is legitimate, I'm ready to exchange further on this topic ;)

**Comment by valentindeaconu** [comment]
Hello,
I find this request reasonable and I will be more than happy to help you add support for all of the clouds. In terms of implementation, should be one resolver implementation for each of the cloud providers, as long as they support generating pre-signed URLs.
I am currently working on introducing the resolver's flow on providers, which was removed a few weeks back (#14) because of a bug: the files uploaded to S3 had different checksums than the original ones because of the way they were downloaded and archived using _go-getter_ and _zipper_.

> 2. possibility to define a private storage at the authority level (eg. authority A uses AWS whereas authority B uses GCS)

In my opinion, I don't see a use-case for this feature. This will only complicate things, requiring the application to find the resolver at run-time. What happens if the user changes the authority resolver? Do we have to implement a method to migrate everything from one resolver to another?

> 3. possibility to define a private storage at the API resource level (eg. AWS for modules and GCS providers)

On the other hand, I agree with this and I also thought of adding this possibility in the future. Right now, the application uses the `storage-resolver` flag to control the resolvers for both modules and providers. I think we can easily add this feature by dividing this flag into `modules-storage-resolver` and `providers-storage-resolver` and instantiate one or two resolvers depending on those flags' values.

**Comment by LoicSikidi** [comment]
Hi @valentindeaconu,

Thank you for your feedback!

Sorry for the late answer I was in vacation 😅.

I'll work on the addition of a gcs resolver and submit a PR soon 🚀.

**Comment by tszebeni** [comment]
Hi,
 is there any update on this feature request?
I would also be interested in a private terraform registry, which can utilize gcs as backend for modules.

**Comment by valentindeaconu** [comment]
Hello!
I'm currently busy with a different project I'm working on and I don't have any bandwidth to implement this. The implementation should not be that hard, but for at least 2 months I don't think I can go back to this.
If anyone here is interested in contributing to this feature, I'm more than happy to review and release it.
